// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package types

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson8ceb9162DecodeGithubComQordobacodeCliV2PkgTypes(in *jlexer.Lexer, out *ScoreResponseBody) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "snapshotTime":
			out.SnapshotTime = int64(in.Int64())
		case "documentScore":
			out.DocumentScore = float64(in.Float64())
		case "breakdown":
			if in.IsNull() {
				in.Skip()
				out.Breakdown = nil
			} else {
				in.Delim('[')
				if out.Breakdown == nil {
					if !in.IsDelim(']') {
						out.Breakdown = make([]Breakdown, 0, 1)
					} else {
						out.Breakdown = []Breakdown{}
					}
				} else {
					out.Breakdown = (out.Breakdown)[:0]
				}
				for !in.IsDelim(']') {
					var v1 Breakdown
					(v1).UnmarshalEasyJSON(in)
					out.Breakdown = append(out.Breakdown, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8ceb9162EncodeGithubComQordobacodeCliV2PkgTypes(out *jwriter.Writer, in ScoreResponseBody) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"snapshotTime\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.SnapshotTime))
	}
	{
		const prefix string = ",\"documentScore\":"
		out.RawString(prefix)
		out.Float64(float64(in.DocumentScore))
	}
	{
		const prefix string = ",\"breakdown\":"
		out.RawString(prefix)
		if in.Breakdown == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Breakdown {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ScoreResponseBody) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8ceb9162EncodeGithubComQordobacodeCliV2PkgTypes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ScoreResponseBody) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8ceb9162EncodeGithubComQordobacodeCliV2PkgTypes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ScoreResponseBody) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8ceb9162DecodeGithubComQordobacodeCliV2PkgTypes(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ScoreResponseBody) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8ceb9162DecodeGithubComQordobacodeCliV2PkgTypes(l, v)
}
func easyjson8ceb9162DecodeGithubComQordobacodeCliV2PkgTypes1(in *jlexer.Lexer, out *Breakdown) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "category":
			out.Category = string(in.String())
		case "issueCount":
			out.IssueCount = int(in.Int())
		case "score":
			out.Score = float64(in.Float64())
		case "enabled":
			out.Enabled = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8ceb9162EncodeGithubComQordobacodeCliV2PkgTypes1(out *jwriter.Writer, in Breakdown) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix[1:])
		out.String(string(in.Category))
	}
	{
		const prefix string = ",\"issueCount\":"
		out.RawString(prefix)
		out.Int(int(in.IssueCount))
	}
	{
		const prefix string = ",\"score\":"
		out.RawString(prefix)
		out.Float64(float64(in.Score))
	}
	{
		const prefix string = ",\"enabled\":"
		out.RawString(prefix)
		out.Bool(bool(in.Enabled))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Breakdown) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8ceb9162EncodeGithubComQordobacodeCliV2PkgTypes1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Breakdown) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8ceb9162EncodeGithubComQordobacodeCliV2PkgTypes1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Breakdown) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8ceb9162DecodeGithubComQordobacodeCliV2PkgTypes1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Breakdown) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8ceb9162DecodeGithubComQordobacodeCliV2PkgTypes1(l, v)
}
