qordoba:
  access_token: some_token
  organization_id: 3001
  workspace_id: 2879
  audiences_map: {}
push:
  sources:
    files:
      - C:\data\golang-example\qordoba-example-formats\pot2\core.qordoba-pot2
      - C:\data\golang-example\qordoba-example-formats\resx\exaple.resx
    folders:
download:
  targets: []
blacklist:
  sources: []
base_url: https://app.qordobatest.com/
